"""Resolve a base workflow by name and produce one workflow's desired text.

Rendering is pure: a base's text in, a workflow's text out, no repository touched. The
caller compares the result against what is deployed and performs only the writes the
difference demands. [LAW:effects-at-boundaries]
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from .config import HOME_BASE_DIR, REPO_BASE_DIR, Config, ConfigError, WorkflowSpec
from .workflow import Binding, WorkflowError, bind, headed, parse, render as to_yaml

BASE_SUFFIX = ".yml"


@dataclass(frozen=True)
class Rendered:
    """One workflow's desired text, and the base file that produced it."""

    path: str
    text: str
    base_file: str


def base_dirs(repo_root: Path, home: Path) -> tuple[Path, ...]:
    """Where a base is looked for, most specific first."""
    return (repo_root / REPO_BASE_DIR, home / HOME_BASE_DIR)


def _locate(name: str, spec_path: str, repo_root: Path, home: Path) -> tuple[str, str]:
    """The first base with this name: its text, and the file it came from.

    A repository ships its own workflow shape by dropping a file in the first of these
    directories, and keeps every other part of its configuration. It never forks the
    installer — which is the difference between a shape one repo needs and a fork that
    stops receiving everything else. [LAW:composability]
    """
    filename = name + BASE_SUFFIX
    for directory in base_dirs(repo_root, home):
        candidate = directory / filename
        if candidate.is_file():
            return candidate.read_text(), str(candidate)

    packaged = resources.files(__package__).joinpath("bases", filename)
    if packaged.is_file():
        return packaged.read_text(), f"(shipped) {filename}"

    searched = ", ".join(str(d) for d in base_dirs(repo_root, home))
    raise ConfigError(
        f"workflows.{spec_path}: no base named {name!r}. Looked for {filename} in "
        f"{searched}, and in the bases shipped with this installer."
    )


def _header(spec: WorkflowSpec) -> str:
    """The banner a rendered workflow carries instead of its base's own.

    It says the file is generated, because the installer overwrites it on every run —
    an edit here appears to work and is undone the next time anyone installs, which is
    the worst of both: the change is lost AND the author believes it landed.
    [LAW:no-silent-failure]

    It names the whole search path rather than the file that won, because the reader's
    question is "where do I put mine", and answering only "where did this one come
    from" sends them to edit a file shipped inside a package.

    Every path here is written the way a human writes it — repo-relative, and `~` for
    home — and NOT as the absolute path this run resolved. A generated file that
    records the machine that generated it renders differently for every developer, so
    the installer would commit a fresh churn of it on each of their machines, forever.
    [FRAMING:representation]
    """
    places = [
        (f"{REPO_BASE_DIR}/{spec.base}{BASE_SUFFIX}", "this repository"),
        (f"~/{HOME_BASE_DIR}/{spec.base}{BASE_SUFFIX}", "this machine"),
    ]
    column = max(len(path) for path, _ in places)
    searched = "\n".join(f"#   {path:{column}}   ({whose})" for path, whose in places)
    return (
        f"# GENERATED by `copirate-review install` from the `{spec.base}` base — do not\n"
        f"# edit by hand. The installer re-renders this file on every run and overwrites\n"
        f"# local edits silently, so an edit here appears to work and is undone the next\n"
        f"# time anyone installs. [LAW:one-source-of-truth]\n"
        f"#\n"
        f"# To change the SHAPE of this workflow — its triggers, permissions, or steps —\n"
        f"# edit the base. It is resolved from the first of these that exists, then the\n"
        f"# bases shipped in promptctl/copirate-code-review-agent:\n"
        f"{searched}\n"
        f"#\n"
        f"# To change the ACTION REF, the SECRETS it is passed, or the INPUTS below, edit\n"
        f"# .copirate-review.yaml (or the layers above it) and re-run the installer.\n"
    )


def resolve_action_ref(config: Config, repo: str) -> str:
    """The `uses:` ref for this repo — `./` in the action's own source repository.

    The action's source repo must review each PR with THAT PR's code, which is the one
    thing a released `@v1` cannot do for it: a change to the reviewer that no run ever
    executed is a change the repo ships untested.

    This is the whole accommodation, and its shape is the point — it selects a VALUE and
    nothing else, so the same base converges here as everywhere and every future base
    change reaches this repo like any other consumer. An exemption that skipped
    convergence instead is precisely how a deployed workflow and its base drift into two
    representations of one thing: an operation that does not run cannot receive a
    change. [LAW:dataflow-not-control-flow]

    The discriminator derives from `action_ref`, so "which repo is the action" is not a
    second copy free to drift from it. [LAW:one-source-of-truth]

    Compared case-insensitively, because GitHub owner/name are: gh reports the canonical
    casing while `action_ref` carries whatever a human typed, and an exact comparison
    misses on `PromptCtl/...` vs `promptctl/...`. The miss is silent and it is precisely
    the failure above — the action's own repo would review its PRs with the RELEASED
    ref, so a change to the reviewer ships having reviewed nothing with itself.
    """
    owner_and_name = config.action_ref.split("@")[0]
    return "./" if repo.casefold() == owner_and_name.casefold() else config.action_ref


def render(
    config: Config, spec: WorkflowSpec, action_ref: str, repo_root: Path, home: Path
) -> Rendered:
    """Parse the base, rebind it from the configuration, and serialize the result.

    A base that is malformed, or that carries no review step to bind, is the operator's
    file to fix — so it leaves here as the same kind of error a malformed config does,
    and reaches the same exit code. A pydantic traceback would report a configuration
    error as "the world did not cooperate". [LAW:parse-dont-validate]
    """
    text, base_file = _locate(spec.base, spec.path, repo_root, home)
    binding = Binding(
        action_ref=action_ref,
        secrets=tuple(sorted(config.secrets)),
        inputs=spec.inputs,
    )
    try:
        bound = bind(parse(text, base_file), binding, base_file)
    except WorkflowError as exc:
        raise ConfigError(f"workflows.{spec.path}: {exc}") from exc

    header = _header(spec)
    return Rendered(path=spec.path, text=to_yaml(headed(bound, header)), base_file=base_file)
